### List users (already working)
GET http://localhost:8080/admin/users

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "adminBrandon",
  "password": "1234"
}